# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
    os: ubuntu-22.04
    tools:
        python: "3.11"
    jobs:
        post_create_environment:
            # - pwd
            # - which python
            # - python -c "import sys;print(sys.path)"
            # - python -m pip install --upgrade pip
            # # Install poetry
            - python -m pip install poetry
            # # Tell poetry to use a virtual environment
            - poetry config virtualenvs.create false ----local
            # # Install project's dependencies
            # - poetry install --with docs
            - poetry install
            # - python -m pip install autoapi
            # - ls -al /home/docs/checkouts/readthedocs.org/user_builds/autoread-dotenv/envs/latest/lib/python3.11/site-packages
            # # - poetry add autoapi

            # - python -m pip install -e .
            # - python -c "import markupsafe;markupsafe.__path__"
            # - python -c "import autoapi;autoapi.__path__"
            # - make install
            # - python -m pip install  -r docs/requirements.txt

formats:
    - htmlzip
    - pdf
    - epub
    # - all

# python:
#     install:
#         - method: pip
#           path: .
# extra_requirements:
#   - docs

sphinx:
    configuration: docs/conf.py
    fail_on_warning: false # true is too strict
